name: Run JUnit 5 tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: maven

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Set unique Chrome user data dir
        run: echo "CHROME_USER_DATA_DIR=/tmp/chrome-profile-${GITHUB_RUN_ID}" >> $GITHUB_ENV

      - name: Run tests with Maven
        run: mvn test
        env:
          FIRST_USER_LOGIN: ${{ secrets.FIRST_USER_LOGIN }}
          FIRST_USER_PASSWORD: ${{ secrets.FIRST_USER_PASSWORD }}
          FIRST_USER_NAME: ${{ secrets.FIRST_USER_NAME }}
          SECOND_USER_LOGIN: ${{ secrets.SECOND_USER_LOGIN }}
          SECOND_USER_PASSWORD: ${{ secrets.SECOND_USER_PASSWORD }}
          SECOND_USER_ID: ${{ secrets.SECOND_USER_ID }}
          SECOND_USER_NAME: ${{ secrets.SECOND_USER_NAME }}
          CHROME_USER_DATA_DIR: ${{ env.CHROME_USER_DATA_DIR }}